baseURL = 'https://a626677909.github.io/'
locale = 'en-us'
title = '侯凌的小屋'
theme = "PaperMod"
[params]
    mainSections = ["posts"]

[params.homeInfoParams]
    Title = "你好，欢迎来到我的博客 👋"
    Content = "这是我用 Hugo 搭建的第一个站点，托管在 GitHub 上。"

[[params.socialIcons]]
    name = "github"
    url = "https://github.com/a626677909"
